// <auto-generated />
using System;
using KerashineERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KerashineERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719124334_PRO_ProductionReceipt")]
    partial class PRO_ProductionReceipt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_Item", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HsCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ItemSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SizeUOM")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("UOMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "ItemId");

                    b.HasIndex("CompanyID", "CategoryId");

                    b.HasIndex("CompanyID", "UOMId");

                    b.ToTable("INV_Item");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_SET_Category", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "CategoryId");

                    b.ToTable("INV_SET_Category");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_SET_UOM", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("UOMId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("UOMCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UOMName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "UOMId");

                    b.ToTable("INV_SET_UOM");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_StockTransactionDetail", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<long>("StockTransactionID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("TransactionDetailID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "StockTransactionID", "TransactionDetailID");

                    b.HasIndex("CompanyID", "ItemID");

                    b.ToTable("INV_StockTransactionDetail");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_StockTransactionHeader", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<long>("StockTransactionID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<int>("DocumentNo")
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int");

                    b.Property<int>("FiscalID")
                        .HasColumnType("int");

                    b.Property<int?>("FromLocationID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint");

                    b.Property<int?>("ToLocationID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "StockTransactionID");

                    b.HasIndex("CompanyID", "DocumentTypeID");

                    b.HasIndex("CompanyID", "FiscalID");

                    b.HasIndex("CompanyID", "FromLocationID");

                    b.HasIndex("CompanyID", "ToLocationID");

                    b.ToTable("INV_StockTransactionHeader");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Business", b =>
                {
                    b.Property<int>("BusinessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessID"));

                    b.Property<string>("BusinessCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("BusinessID");

                    b.ToTable("SET_Business");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BusinessID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NTNNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("STRNNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID");

                    b.HasIndex("BusinessID");

                    b.ToTable("SET_Company");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_DocumentType", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("DocumentTypeID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "DocumentTypeID");

                    b.ToTable("SET_DocumentType");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Fiscal", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FiscalID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "FiscalID");

                    b.ToTable("SET_Fiscal");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Location", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("LocationID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "LocationID");

                    b.ToTable("SET_Location");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_MaterialIssueDetail", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IssueID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("IssueDetailID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<decimal>("IssuedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaterialCompanyID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequiredQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int?>("UOMCompanyID")
                        .HasColumnType("int");

                    b.Property<int>("UOMId")
                        .HasColumnType("int");

                    b.Property<int?>("UOMId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompanyID", "IssueID", "IssueDetailID");

                    b.HasIndex("MaterialCompanyID", "MaterialItemId");

                    b.HasIndex("UOMCompanyID", "UOMId1");

                    b.ToTable("PRO_MaterialIssueDetail");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_MaterialIssueHeader", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IssueID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionOrderID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "IssueID");

                    b.HasIndex("CompanyID", "ProductionOrderID");

                    b.ToTable("PRO_MaterialIssueHeader");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionOrderDetail", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductionOrderID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ProductionOrderDetailID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<decimal>("IssuedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RequiredQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int?>("UOMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CompanyID", "ProductionOrderID", "ProductionOrderDetailID");

                    b.HasIndex("CompanyID", "MaterialID");

                    b.HasIndex("CompanyID", "UOMId");

                    b.ToTable("PRO_ProductionOrderDetail");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionOrderHeader", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductionOrderID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("BatchSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchSizeUOM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductionOrderNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "ProductionOrderID");

                    b.HasIndex("CompanyID", "ProductID");

                    b.HasIndex("CompanyID", "RecipeID");

                    b.ToTable("PRO_ProductionOrderHeader");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionReceiptHeader", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<int>("ProductionOrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "ReceiptID");

                    b.HasIndex("CompanyID", "ProductionOrderID");

                    b.ToTable("PRO_ProductionReceiptHeader");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_RecipeDetail", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RecipeID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("RecipeDetailID")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int>("UOMId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CompanyID", "RecipeID", "RecipeDetailID");

                    b.HasIndex("CompanyID", "MaterialID");

                    b.HasIndex("CompanyID", "UOMId");

                    b.ToTable("PRO_RecipeDetail");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_RecipeHeader", b =>
                {
                    b.Property<int>("CompanyID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RecipeID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("BatchSize")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BatchSizeUOM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CreatedByValue");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UpdatedByValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UpdatedByValue");

                    b.HasKey("CompanyID", "RecipeID");

                    b.HasIndex("CompanyID", "ProductID");

                    b.ToTable("PRO_RecipeHeader");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_Item", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_SET_Category", "Category")
                        .WithMany()
                        .HasForeignKey("CompanyID", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Inventory.INV_SET_UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("CompanyID", "UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_StockTransactionDetail", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Item")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Inventory.INV_StockTransactionHeader", "Header")
                        .WithMany("StockTransactionDetail")
                        .HasForeignKey("CompanyID", "StockTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_StockTransactionHeader", b =>
                {
                    b.HasOne("KerashineERP.Models.Master.SET_DocumentType", "FK_INV_StockTransactionHeader_SET_DocumentType")
                        .WithMany()
                        .HasForeignKey("CompanyID", "DocumentTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Master.SET_Fiscal", "FK_INV_StockTransactionHeader_SET_Fiscal")
                        .WithMany()
                        .HasForeignKey("CompanyID", "FiscalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Master.SET_Location", "FK_INV_StockTransactionHeader_SET_Location_From")
                        .WithMany()
                        .HasForeignKey("CompanyID", "FromLocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KerashineERP.Models.Master.SET_Location", "FK_INV_StockTransactionHeader_SET_Location_To")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ToLocationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FK_INV_StockTransactionHeader_SET_DocumentType");

                    b.Navigation("FK_INV_StockTransactionHeader_SET_Fiscal");

                    b.Navigation("FK_INV_StockTransactionHeader_SET_Location_From");

                    b.Navigation("FK_INV_StockTransactionHeader_SET_Location_To");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Company", b =>
                {
                    b.HasOne("KerashineERP.Models.Master.SET_Business", "Business")
                        .WithMany("Companies")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_MaterialIssueDetail", b =>
                {
                    b.HasOne("KerashineERP.Models.Production.PRO_MaterialIssueHeader", "Header")
                        .WithMany("IssueDetails")
                        .HasForeignKey("CompanyID", "IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialCompanyID", "MaterialItemId");

                    b.HasOne("KerashineERP.Models.Inventory.INV_SET_UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMCompanyID", "UOMId1");

                    b.Navigation("Header");

                    b.Navigation("Material");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_MaterialIssueHeader", b =>
                {
                    b.HasOne("KerashineERP.Models.Production.PRO_ProductionOrderHeader", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ProductionOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionOrderDetail", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Material")
                        .WithMany()
                        .HasForeignKey("CompanyID", "MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Production.PRO_ProductionOrderHeader", "Header")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CompanyID", "ProductionOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Inventory.INV_SET_UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("CompanyID", "UOMId");

                    b.Navigation("Header");

                    b.Navigation("Material");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionOrderHeader", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Product")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Production.PRO_RecipeHeader", "Recipe")
                        .WithMany()
                        .HasForeignKey("CompanyID", "RecipeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionReceiptHeader", b =>
                {
                    b.HasOne("KerashineERP.Models.Production.PRO_ProductionOrderHeader", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ProductionOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_RecipeDetail", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Material")
                        .WithMany()
                        .HasForeignKey("CompanyID", "MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Production.PRO_RecipeHeader", "RecipeHeader")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("CompanyID", "RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KerashineERP.Models.Inventory.INV_SET_UOM", "UOM")
                        .WithMany()
                        .HasForeignKey("CompanyID", "UOMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("RecipeHeader");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_RecipeHeader", b =>
                {
                    b.HasOne("KerashineERP.Models.Inventory.INV_Item", "Product")
                        .WithMany()
                        .HasForeignKey("CompanyID", "ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KerashineERP.Models.Inventory.INV_StockTransactionHeader", b =>
                {
                    b.Navigation("StockTransactionDetail");
                });

            modelBuilder.Entity("KerashineERP.Models.Master.SET_Business", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_MaterialIssueHeader", b =>
                {
                    b.Navigation("IssueDetails");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_ProductionOrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("KerashineERP.Models.Production.PRO_RecipeHeader", b =>
                {
                    b.Navigation("RecipeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
